### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Jjagg** [GrahamTheCoder/Semver-AssemblyCompatibility#4]
Hey Graham! 

I was surprised and kind of disappointed there was no official tool for comparing APIs and tooling for SemVer from dotnet since NuGet is a first-class citizen and it recommends Semantic Versioning. So I was quite happy when I came across this project :)

I've ported this project to .NET Core and would like to extend it (mostly with the suggestions in the issues you've opened here) and release it as a dotnet CLI extension. Credit where credit is due of course, but I noticed you haven't added a license for the project. Could you add one please?

**Comment by GrahamTheCoder** [comment]
Sorry for the huge delay @Jjagg! I've now added a license file.
I'd be happy to accept a dot net core PR.
